
import java.awt.event.ActionEvent;

import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 * Team One
 * GUI Implementation
 * Gomoku
 * CSCE 320 - Spring 2015
 * 3/16/2015
 * Java - JVM
 * Sources:
 * 
 * Revisions:
 * 3/14/2015 - View created by Karen Bullinger.
 */
public class LeaderboardView extends javax.swing.JPanel {
DefaultTableModel model;
LeaderboardController controller;
String[] columnNames = {"Username","Wins","Losses", "Win/Loss %"};
Object[][] data = {};
    /**
     * Creates new form LeaderboardView
     */
    public LeaderboardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        quitB = new javax.swing.JButton();
        board = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        lobbyB = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Gomoku");

        quitB.setText("Quit");
        quitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBActionPerformed(evt);
            }

			
        });
        
        model = new DefaultTableModel(data, columnNames);
        topTenTable = new JTable(model);

        
        topTenTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        topTenTable.setRowHeight(25);
        topTenTable.setShowHorizontalLines(true);
        topTenTable.getTableHeader().setResizingAllowed(false);
        topTenTable.getTableHeader().setReorderingAllowed(false);
        topTenTable.setUpdateSelectionOnSort(false);
        topTenTable.setVerifyInputWhenFocusTarget(false);
        board.getViewport().add(topTenTable);
        

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Leaderboard");
        jLabel2.setToolTipText("");

        lobbyB.setText("Lobby");
        lobbyB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lobbyBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quitB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lobbyB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lobbyB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void lobbyBActionPerformed(ActionEvent evt) {
		controller.statsLobbyTrans();	
	}
    
    private void quitBActionPerformed(ActionEvent evt) {
		System.exit(0);
		
	}
    
    public void updateTable(String[] m){
        double winLoss;
       for(int i = 1; i < m.length ; i+=3){
           int win = Integer.parseInt(m[i+1]);
           int loss = Integer.parseInt(m[i+2]);
           if(win == 0 && loss == 0){
            winLoss = 0.0;
           }
           else
             winLoss = ((double)win/((double)win+loss))*100.0;
           
         model.insertRow(topTenTable.getRowCount(), new Object[]{m[i], m[i+1], m[i+2], winLoss});
        }
       RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(model);
       topTenTable.setRowSorter(sorter);
    
    }
    public void setController(LeaderboardController cont){
     this.controller = cont;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane board;
    private javax.swing.JButton lobbyB;
    private javax.swing.JButton quitB;
    private javax.swing.JTable topTenTable;
    // End of variables declaration//GEN-END:variables
}
