
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PLUCSCE
 */
public class GameView extends javax.swing.JPanel {
    private final int PLAYERONE = 1;
    
    private final JButton[][] grid;
    private Map<JButton, String> buttonMap = new HashMap();
    //private GameController controller;
    private int x;
    private int y;
    private String[] move;
    
    private final ActionListener listener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            JButton pressedButton = (JButton)e.getSource();
            //System.out.println(buttonMap.get(pressedButton));
            move = buttonMap.get(pressedButton).split(" ");
            x = Integer.parseInt(move[0]);
            y = Integer.parseInt(move[1]);
            //moveMade(x, y, PLAYERONE);
            pressedButton.setBackground(Color.BLUE);
            pressedButton.setEnabled(false);
        }
    };

    /**
     * Creates new form GameView
     * @param width
     * @param length
     */
    public GameView(int width, int length){ //constructor
        this.setLayout(new GridLayout(width,length)); //set layout
        grid=new JButton[width][length]; //allocate the size of grid
        for(int y=0; y<length; y++){
                for(int x=0; x<width; x++){
                        grid[x][y]=new JButton(); //creates new button 
                        grid[x][y].addActionListener(listener);
                        this.add(grid[x][y]); //adds button to grid
                        buttonMap.put(grid[x][y], Integer.toString(x) + " " + Integer.toString(y));
                }
        }
        //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //frame.pack(); //sets appropriate size for frame
        //frame.setVisible(true); //makes frame visible
    }
    
    /*public void moveMade(int x, int y, int player)
    {
        controller.moveMade(x, y, player);
    }
    */
    /*public void setController(GameController cont)
    {
        controller = cont;
    }
    */
    public void opponentMove(int x, int y)
    {
        grid[x][y].setBackground(Color.RED);
        grid[x][y].setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
