
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class GameView extends javax.swing.JPanel {

    private JButton[][] grid;
    private Map<JButton, String> buttonMap = new HashMap<JButton, String>();
    private GameController controller;
    private Constants consts = new Constants();
    private int width;
    private int length;
    private String[] coordinates;
    private final ActionListener listener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            JButton pressedButton = (JButton) e.getSource();
            System.out.println(buttonMap.get(pressedButton));
            coordinates = buttonMap.get(pressedButton).split(" ");
            String response = controller.validateSelf(Integer.parseInt(coordinates[0]), Integer.parseInt(coordinates[1]));
            if (response.equals("valid")) {
                pressedButton.setBackground(Color.BLUE);
                pressedButton.setEnabled(false);

            } else if (response.equals("invalid")) {
                displayErrorMessage("That move is invalid.");
            } else if (response.equals("win")) {
                pressedButton.setBackground(Color.BLUE);
                pressedButton.setEnabled(false);
                win();
            }
        }
    };

    /**
     * Creates new form GameView
     */
    public GameView() {
        initComponents();
        gameView(30, 30);
    }

    public void gameView(int w, int l) {
        this.length = l;
        this.width = w;
        //this.setLayout(new BorderLayout());
        game.setLayout(new GridLayout(width, length));
        this.add(game, BorderLayout.CENTER);

        grid = new JButton[width][length]; //allocate the size of grid
        for (int y = 0; y < length; y++) {
            for (int x = 0; x < width; x++) {
                grid[x][y] = new JButton(); //creates new button 
                grid[x][y].addActionListener(listener);
                //grid[x][y].setPreferredSize(new java.awt.Dimension(20,20));
                game.add(grid[x][y]); //adds button to grid
                buttonMap.put(grid[x][y], Integer.toString(x) + " " + Integer.toString(y));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        game = new javax.swing.JPanel();
        quitB = new javax.swing.JButton();
        gameNotificationL = new javax.swing.JLabel();
        resignB = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gomoku");

        game.setMaximumSize(new java.awt.Dimension(400, 400));
        game.setMinimumSize(new java.awt.Dimension(400, 400));
        game.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout gameLayout = new javax.swing.GroupLayout(game);
        game.setLayout(gameLayout);
        gameLayout.setHorizontalGroup(
            gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        gameLayout.setVerticalGroup(
            gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        quitB.setText("Quit");
        quitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBActionPerformed(evt);
            }
        });

        resignB.setText("Resign");
        resignB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resignBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(gameNotificationL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quitB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resignB)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(gameNotificationL)
                .addGap(18, 18, 18)
                .addComponent(game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitB)
                    .addComponent(resignB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void updateTurnNotification(boolean b){
        if(b){
        gameNotificationL.setText("It's your turn!");
        }
        else
        gameNotificationL.setText("It's not your turn.");
    }
    
    private void quitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitBActionPerformed

    private void resignBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resignBActionPerformed
        controller.resign();
    }//GEN-LAST:event_resignBActionPerformed

    public void displayMove(int x, int y) {
        grid[x][y].setBackground(Color.RED);
        grid[x][y].setEnabled(false);
    }

    /**
     * Error message pop up box.
     *
     * @param errorMessage
     */
    public void displayErrorMessage(String errorMessage) {
        JOptionPane.showMessageDialog(this, errorMessage);
    }

    public void setController(GameController cont) {
        this.controller = cont;
    }

    public void win() {
        displayErrorMessage("You Win!");
        System.out.println(controller.loggedIn());
        if(controller.aiGame && !controller.loggedIn()){
           controller.switchToLogin();
        }
        else
            controller.switchToLobby();
    }

    public void lose() {
        displayErrorMessage("You Lose!");
        if(controller.aiGame && !controller.loggedIn()){
                controller.switchToLogin();
        } else
            controller.switchToLobby();
    }

    public void resetBoard() {
        for (int y = 0; y < length; y++) {
            for (int x = 0; x < width; x++) {
                grid[x][y].setBackground(null);
                grid[x][y].setEnabled(true);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel game;
    private javax.swing.JLabel gameNotificationL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton quitB;
    private javax.swing.JButton resignB;
    // End of variables declaration//GEN-END:variables
}
