
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Karen
 */
public class LobbyViewold extends javax.swing.JPanel {
        DefaultListModel<String> onlineModel;
        LobbyController controller ;

    /**
     * Creates new form TestLobbyView
     */
    public LobbyViewold() {
       
        initComponents();
              
    }
    
   
    
     public void setController(LobbyController lc)
    {
        this.controller = lc;
    }
     public void setLobbyView(LobbyView v)
   {
       controller.setLobbyView(v);
   }
     
      public void updateOnlinePlayerList(String[] online) {
        for(int i = 1 ; i< online.length; i++){
          onlineModel.addElement(online[i]);
       }

      }

      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        onlineModel = new DefaultListModel<>(); 
        onlinePlayersList = new JList<>(onlineModel);

        onlinePlayersPane = new JScrollPane(onlinePlayersList);
        onlinePlayersList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        //onlinePlayersPane.setViewportView(onlinePlayersList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(onlinePlayersPane, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(onlinePlayersPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JList<String> onlinePlayersList;
    private JScrollPane onlinePlayersPane;
    // End of variables declaration//GEN-END:variables
}
